spring.application.name=ibfd

app.article-xml=classpath:xml/wtj_2018_04_int_1.xml
app.collections-xml=classpath:config/collections.xml
app.xsl=classpath:xslt/article-to-html.xsl
app.schematron=classpath:schematron/pubdate-validation.sch
app.xsd=classpath:xsd/ibfd-article.xsd
